#!/bin/bash
kubectl cp config.sh gcloud-sdk:/root -c init-pd
echo 'ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidHBpLWR0ZC1z
ZXJ2aWNlIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMmM1NGUxNDAwNmMyY2MzOTRmY2ZjMGZhZjdk
MmMxMDk0OTljYTYxMyIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVkt
LS0tLVxuTUlJRXVnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS1F3Z2dTZ0FnRUFBb0lCQVFD
eHloeEpxakFSWW1Jc1xuVDZEMHlWRWRBbnN6RmZmaXRYRHpueE1hbktQN0NXQmZMa2E5S2xLREFP
NEZUVWhPbkNQSUlSMWxHbVhXWkE0RVxubmY3V09qMHBYczFpV215OG1DTlVoeHp0eGJvbkplbUNC
aFIxMjdpb0NGYW02NmxFMllqWHJxclExTWJodTFwR1xuMnQvK2RDeWQzRkVZNVp0c0xVMk96Zjd5
Mk5ZWXd4bXVXbXkvT1k3aGZ5RlYzZVR1VzRPakgwelNzREJIVzkrUlxuMlhEemMvRVMyOG1NR3Ft
MjhPVFlEM2hNM0Zlak1QSnFqa0ZOWmp2TjdrUUpscVBDSFFNaWdXaWdxT2pZQk4wcFxuTHVPMW9Q
MEpuYXRPRFFHZGR6S2hLU1c3UXdCKzFsdTcwdEZIUUJ0WlE0eGtmMVY3ZE5aTmhGeGtGdDNuNGpF
Z1xueSs2OXFDVUpBZ01CQUFFQ2dmOGpsNUtTTEwveXV2OXNYNFNaZkxRQVdyN1BPMWFrekM0UWw0
ZjdpK0JJSVZocFxudFpuenhNVS85Syt4NEFiWnRlaHo2QzA2VUU2UzNQVHhkNi9NczF3TExDOXh3
U2lEbVBGNXVwTFFCd1Y5VU5tdVxuYmdrcWp4SW9rWUxIWitZN0lsR0MzRFRXR2NLMjdncmtwR3l6
UkE2cWk3Q3dpMGJTSVQrbGx4ZXpCalhXUHVLZlxuUlhPM1RKS2tpSHNCcnRLbDl0YTFEbjQxRmNp
N1pldzJhOG5Ec1R1VTBYcm5YbDRTeVdNOFVqeG5sOXZqZ0dpMFxuVzFJZ0UrNU1RL2dVTVd5dmNI
S092UkdzdTFETWRzMFV1SUx0SUluSFRHSXBzVkZRakhEZmsyRTFWaFdsbVQ0QlxuQmNGYWxDYi8x
OUhicXlWV21LNjg5VHBJTXpKRTlRNVlFOGNRTVlFQ2dZRUE4RU5QMUFma1I1bmtoNWRwWEVITFxu
U1lqUjRTT1dTaWFmMXNuazd3VlgzTDM3T0NmejZxNTBOVldNN0kwS0Vpa0o0RHVWWk9GRGErMlBr
L0lYTjdNYVxubUliTnRBSitCWHRCT1A5dVN3amFvVXRqbGl1V0tKUit3bXZZMHh0Z0xkSEVzc25s
ZVQ3VnBYK2hZeXpSRkJ3WlxudDRsSFdZWGdneFZHckpuTk1TQXlNVWtDZ1lFQXZXOUJMQ0s0L0tT
N3M4VWh0N2pkdDErQ0hqQ1ZraC9TL1AwdlxuTWxTYmVCMnRENmhYVjZ5T1hQcVpLbmIvS05pQi9t
d1ZkTjBJVHAremhTbHJiS3FKM3NLNzBJWXY3bk1ZRDFWWlxudkNlMlRUcXNLVThLVFNLZFArVlBE
d1UxQnpXRkdoSlNjdUFKQmxHS0ZycmNjTXJLS0ZXazFMYWMzTmxWTlprUFxubmJHV0ZjRUNnWUF5
bUdveUkydE9MTGswV0kxR2NWQ0c3cm9MNkR1WTUrTlhEdk1YNW84bkhCYlFMNUd0QlFuUlxueFc5
RXpUcW1zbCt6Q2JrZklsVFpZSkNRdmpWbmRGOFFhYXJkMG55SldQaFdNV3dmZndEVFlKWGJKTmlk
T1JBc1xuanh0ODhWSGl0RDd3eTVWNFgrUUwwd0hBYWNxcHFuVTc4anZGUFcwWERaN3hiLzRHNzFu
Q2lRS0JnSFN3ZmFMa1xuV0xNMy9tL0VkUHFwSTlwN09MbkVENzZOWC9oN05ZRjVZTE5qQkdIcXZy
TEJGb2pyelVHOVAzdzNzZ3U1SkpaeVxuT1ZYRlJsNDJuM2UycldyTTVjaVRnQjhRUXJmZlNZRi9y
T3B4dys5R1F3QTAzRXlwd2tOc1g3ZnJIZXhyY09KV1xuWXZqRGJaNkd5SmVxTTFFWlFJblBXMTBu
ZXplaTYxMm1NTitCQW9HQUtwcStmWVhheVB1dGJ6a0tPdjg4Q0s1RlxuSkp1TWZ3Y2RUa0pGbXd6
RUhESUtCcU8yQVErT29KTWRrbW5oWlRmeHgweWR5Rk03WGFjajBFQSt2VEIrSGR0MFxuUnZHK2l1
ZnBFZEx5VG95Mnpscjl5SmtWZDFWdnN0c0ZCSC9sVE5EdVc4cHVVR2pVVzZzaVdkc08yLzZDZ1kr
Z1xuenN3SGFFcU8rQzJwYVZPWWFkbz1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAg
ImNsaWVudF9lbWFpbCI6ICJkb3dubG9hZC1kaWdpLWNvbmZpZ0B0cGktZHRkLXNlcnZpY2UuaWFt
LmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTE0NjAwNTU3NzE2MzU1NDEw
MzU2IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgy
L2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9r
ZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xl
YXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0
cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9kb3dubG9hZC1k
aWdpLWNvbmZpZyU0MHRwaS1kdGQtc2VydmljZS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAg
InVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo=' | base64 -d > download_config.json
kubectl cp download_config.json gcloud-sdk:/root -c init-pd
kubectl exec -it gcloud-sdk -- gcloud auth activate-service-account download-digi-config@tpi-dtd-service.iam.gserviceaccount.com --key-file=/root/download_config.json --project=tpi-dtd-service
kubectl exec -it gcloud-sdk -- curl -X GET -H "Authorization: Bearer $(gcloud auth print-access-token)" -o "digirunner.tar" "https://storage.googleapis.com/storage/v1/b/digirunner-config/o/digirunner.tar?alt=media"
kubectl exec -it gcloud-sdk -- sh /root/config.sh

kubectl cp gcloud-sdk:/root/application-gcp.properties application-gcp.properties -c init-pd
sed -i "s/DeFault_pW/$DB_PASSWORD/g" ./application-gcp.properties
kubectl cp ./application-gcp.properties gcloud-sdk:/exports/config/application-gcp.properties -c init-pd
kubectl delete pod gcloud-sdk
echo 'Initialization script completed.'
