x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "4.2.4"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    releaseTypes:
      - Feature
    recommended: false
  images:
    '':
      properties:
        imageDigiRepo:
          default: gcr.io/tpisoftware-digirunner-public/digirunner/deployer:4.2.4
          type: FULL
    composer:
      properties:
        imageComposerRepo:
          default: gcr.io/tpisoftware-digirunner-public/composer/deployer:4.2.2
          type: FULL
properties:
  NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    default: digirunner
    x-google-marketplace:
      type: NAMESPACE
  PROJECT_NUM:
    type: string
    default: default
  PROJECT_ID:
    type: string
    default: default
  REGION:
    type: string
    default: asia-east1
required:
- NAME
- NAMESPACE
- PROJECT_NUM
- PROJECT_ID
- REGION
