apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: composer-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTPS
    requestPath: /editor/hello
    port: 8440