apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: digi-keeper-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTPS
    requestPath: /dgrv4/version
    port: 8445